apiVersion: v1
kind: Service
metadata:
  name: github-actions-spring-boot-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: github-actions-spring-boot